"""empty message

Revision ID: 49e9fb6ce41e
Revises: 
Create Date: 2019-11-18 18:59:40.514188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49e9fb6ce41e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_stats_rigs_fan_gpu'), 'stats_rigs', ['fan_gpu'], unique=False)
    op.create_index(op.f('ix_stats_rigs_hash_gpu'), 'stats_rigs', ['hash_gpu'], unique=False)
    op.create_index(op.f('ix_stats_rigs_pw_gpu'), 'stats_rigs', ['pw_gpu'], unique=False)
    op.create_index(op.f('ix_stats_rigs_temp_gpu'), 'stats_rigs', ['temp_gpu'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stats_rigs_temp_gpu'), table_name='stats_rigs')
    op.drop_index(op.f('ix_stats_rigs_pw_gpu'), table_name='stats_rigs')
    op.drop_index(op.f('ix_stats_rigs_hash_gpu'), table_name='stats_rigs')
    op.drop_index(op.f('ix_stats_rigs_fan_gpu'), table_name='stats_rigs')
    # ### end Alembic commands ###
